const Types = {
  INCREASE_COUNT_SAGA: 'INCREASE_COUNT_SAGA',
  DECREASE_COUNT_SAGA: 'DECREASE_COUNT_SAGA',

  ADD_TODO_SAGA: 'ADD_TODO_SAGA',
  DELETE_TODO_SAGA: 'DELETE_TODO_SAGA',
};

export default Types;